# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-10-07 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodsvisitcount',
            options={'verbose_name': '统计分类商品访问量', 'verbose_name_plural': '统计分类商品访问量'},
        ),
        migrations.AlterField(
            model_name='goodsvisitcount',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='统计日期'),
        ),
        migrations.AlterModelTable(
            name='goodsvisitcount',
            table='tb_goods_visit',
        ),
    ]
